<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Rakshit" failures="1" tests="6" name="tests.CheckoutPage.Test_verifyForm" time="108.066" errors="0" timestamp="2025-09-07T22:47:38 IST" skipped="0">
  <testcase classname="tests.CheckoutPage.Test_verifyForm" name="testCheckoutProcess" time="12.023"/>
  <testcase classname="tests.CheckoutPage.Test_verifyForm" name="testCheckoutProcess" time="21.291"/>
  <testcase classname="tests.CheckoutPage.Test_verifyForm" name="testCheckoutProcess" time="21.324"/>
  <testcase classname="tests.CheckoutPage.Test_verifyForm" name="testCheckoutProcess" time="21.121"/>
  <testcase classname="tests.CheckoutPage.Test_verifyForm" name="testCheckoutProcess" time="21.100"/>
  <testcase classname="tests.CheckoutPage.Test_verifyForm" name="testCheckoutProcess" time="11.207">
    <failure message="❌ Expected error but proceeded to Checkout Overview." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: ❌ Expected error but proceeded to Checkout Overview.
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertFalse(Assert.java:65)
at tests.CheckoutPage.Test_verifyForm.testCheckoutProcess(Test_verifyForm.java:61)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCheckoutProcess -->
</testsuite> <!-- tests.CheckoutPage.Test_verifyForm -->
