<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Rakshit" failures="1" tests="7" name="CheckoutPage Tests" time="118.768" errors="0" timestamp="2025-09-07T22:46:20 IST">
  <testcase classname="tests.CheckoutPage.Test_verifyForm" name="testCheckoutProcess" time="0.678"/>
  <testcase classname="tests.CheckoutPage.Test_verifyForm" name="testCheckoutProcess" time="10.63"/>
  <testcase classname="tests.CheckoutPage.Test_verifyForm" name="testCheckoutProcess" time="0.676">
    <failure type="java.lang.AssertionError" message="❌ Expected error but proceeded to Checkout Overview.">
      <![CDATA[java.lang.AssertionError: ❌ Expected error but proceeded to Checkout Overview.
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertFalse(Assert.java:65)
at tests.CheckoutPage.Test_verifyForm.testCheckoutProcess(Test_verifyForm.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- testCheckoutProcess -->
  <testcase classname="tests.CheckoutPage.Test_verifyForm" name="testCheckoutProcess" time="10.734"/>
  <testcase classname="tests.CheckoutPage.Test_verifyForm" name="testCheckoutProcess" time="10.541"/>
  <testcase classname="tests.CheckoutPage.Test_verifyForm" name="testCheckoutProcess" time="10.528"/>
  <testcase classname="tests.CheckoutPage.Test_FinishCheckout" name="testFinishCheckout" time="0.137"/>
</testsuite> <!-- CheckoutPage Tests -->
